Repository Nomik94/LounGe, pull requests merged in 2023-04, with the labels that each got.

#234 Refactor : 코드리뷰 피드백 사항 수정
  public/javascript/auth.js
  src/auth/auth.module.ts
  src/comment/comment.module.ts
  src/comment/comment.service.ts
  src/email/email.controller.ts
  src/email/email.module.ts
  src/email/email.service.ts
  src/user/user.module.ts
  src/user/user.service.ts
  views/findPassword.hbs
Labels: Type: Refactor

#236 Refactor/group
  public/javascript/hub.group.members.js
  src/common/repository/group.repository.ts
  src/group/dto/modify.group.dto.ts
  src/group/group.service.ts
Labels: Type: Refactor

#237 Dev
  public/javascript/auth.js
  public/javascript/hub.group.members.js
  src/auth/auth.module.ts
  src/comment/comment.module.ts
  src/comment/comment.service.ts
  src/common/repository/group.repository.ts
  src/common/repository/newsfeed.repository.ts
  src/common/repository/user.group.repository.ts
  src/email/email.controller.ts
  src/email/email.module.ts
  src/email/email.service.ts
  src/group/dto/modify.group.dto.ts
  src/group/group.service.ts
  src/newsfeed/newsfeed.controller.ts
  src/newsfeed/newsfeed.service.ts
  src/user/user.module.ts
  src/user/user.service.ts
  views/findPassword.hbs
Labels: Type: Refactor

#238 Refactor : accessToken 만료시간 변경
  public/javascript/auth.js
  src/auth/auth.service.ts
Labels: Type: Refactor

#240 Hotfix : 카카오로그인 삭제
  views/auth.hbs
Labels: For: Hotfix

#241 Readme
  README.md
Labels: Type: Docs/Chore

#242 Dev
  README.md
Labels: Type: Docs/Chore
