Repository Nomik94/LounGe, pull requests merged in 2023-03, with the labels that each got.

#30 Feature/register 글로벌 예외처리 및 폴더 이름 변경
  package-lock.json
  package.json
  src/common/filter/http-exception.filter.ts
  src/main.ts
  src/register/dto/register-credential.dto.ts
  src/register/register.controller.spec.ts
  src/register/register.controller.ts
  src/register/register.module.ts
  src/register/register.service.spec.ts
  src/register/register.service.ts
Labels: Type: Feature

#32 Feature/create group 그룹 생성 기능
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.module.ts
  src/database/entities/tag.entity.ts
  src/group/dto/create.group.dto.ts
  src/group/group.controller.spec.ts
  src/group/group.controller.ts
  src/group/group.module.ts
  src/group/group.service.spec.ts
  src/group/group.service.ts
  src/main.ts
  tsconfig.json
Labels: Type: Feature, Type: Test

#36 Feature/grouplist 그룹 리스트 기능
  src/database/entities/user-group.entity.ts
  src/group/group.controller.ts
  src/group/group.service.ts
Labels: Type: Feature

#42 Feat : 그룹 삭제 기능 추가
  src/group/group.controller.ts
  src/group/group.service.ts
Labels: Type: Feature

#44 Refactor : 그룹 서비스 tagCheck 함수 리팩토링
  src/group/group.service.ts
Labels: Type: Refactor

#50 Feature/serchtagnewsfeed 태그로 뉴스피드 검색하기
  src/newsfeed/newsfeed.controller.ts
  src/newsfeed/newsfeed.service.ts
Labels: For: Utils, Type: Feature, Type: Test

#51 Feat : 그룹 가입 신청 및 그룹 가입 신청 수락
  src/group/dto/accept.group.join.dto.ts
  src/group/group.controller.ts
  src/group/group.service.ts
Labels: Type: Feature

#53 Refactor: 뉴스피드 읽기 기능 리팩토링
  src/newsfeed/newsfeed.service.ts
Labels: Type: Refactor

#58 Feat : 그룹 태그 검색
  package-lock.json
  package.json
  src/group/dto/find.group.tag.dto.ts
  src/group/group.controller.ts
  src/group/group.service.ts
Labels: Type: Feature, Type: Refactor

#59 Refactor/file
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/guards/jwt-refresh.guard.ts
  src/email/email.controller.spec.ts
  src/email/email.controller.ts
  src/email/email.module.ts
  src/email/email.service.ts
Labels: Type: Feature

#61 Feat : 그룹 탈퇴 기능
  src/group/group.controller.ts
  src/group/group.service.ts
Labels: Type: Feature

#62 Refactor/serchtagnewsfeed 태그 뉴스피드 검색 기능 수정
  package-lock.json
  package.json
  src/app.module.ts
  src/newsfeed/newsfeed.service.ts
Labels: Type: Refactor

#64 Refactor/newsfeeddto 뉴스피드 작성 시 태그 글자 수 제한
  src/newsfeed/dto/newsfeed-check.dto.ts
Labels: Type: Refactor

#67 Feature/group img 그룹 생성 이미지 업로드
  .gitignore
  package-lock.json
  package.json
  src/group/dto/create.group.dto.ts
  src/group/group.controller.ts
  src/group/group.module.ts
  src/group/group.service.ts
  src/group/utills/group.img.multer.ts
Labels: Type: Feature, Type: Refactor

#70 Feature/userimage
  .gitignore
  package-lock.json
  package.json
  public/img/default/userImage_logo.png
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/utils/user.img.multer.ts
  src/database/entities/user.entity.ts
Labels: Type: Feature

#71 Refactor : 유저 이미지 업로드 수정
  src/auth/auth.service.ts
  src/database/entities/user.entity.ts
  src/group/group.module.ts
Labels: Type: Refactor

#75 Refactor : 뉴스피드 로그인 연동
  src/newsfeed/newsfeed.controller.ts
  src/newsfeed/newsfeed.service.ts
Labels: Type: Refactor

#78 Feature/frontnewsfeed 뉴스피드 그룹 별 읽기
  src/newsfeed/dto/newsfeed-check.dto.ts
  src/newsfeed/newsfeed.controller.ts
  src/newsfeed/newsfeed.module.ts
  src/newsfeed/newsfeed.service.ts
  views/newsfeed.hbs
Labels: Type: Feature, Type: Refactor

#82 Feature/registerpage
  kakao.html
  public/javascript/auth.js
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/email/email.controller.ts
  src/email/email.service.ts
  src/main.ts
  views/auth.hbs
  views/kakao.hbs
Labels: For: views, Type: Refactor

#83 Feature/grouppage
  public/css/raw/calendar.css
  public/img/svg/day.svg
  public/img/svg/month.svg
  public/img/svg/week.svg
  public/javascript/group.list.js
  public/js/calendar.js
  views/events.hbs
Labels: For: views

#84 Refactor : 로그인 시 페이지 이동
  public/javascript/auth.js
Labels: For: views, Type: Refactor

#90 Newsfeed/front 뉴스피드 페이지 연동
  public/javascript/newsfeed.js
  src/newsfeed/newsfeed.controller.ts
  src/newsfeed/newsfeed.module.ts
  src/newsfeed/newsfeed.service.ts
  views/newsfeed.hbs
Labels: Type: Feature

#92 Feat: userEvent DB연결코드 작성(확인및 수정필요)
  src/calendar/calendar.controller.ts
  src/calendar/calendar.module.ts
  src/calendar/calendar.service.ts
  src/calendar/dto/create-groupEvent.dto.ts
  src/calendar/dto/create-userEvent.dto.ts
  src/calendar/dto/delete-event.dto.ts
  src/calendar/dto/delete-groupEvent.dto.ts
  src/calendar/dto/delete-userEvent.dto.ts
  src/calendar/dto/update-event.dto.ts
  src/calendar/dto/update-groupEvent.dto.ts
  src/calendar/dto/update-userEvent.dto.ts
Labels: Type: Feature

#93 Feature/group 그룹 기능
  src/group/group.controller.ts
  src/group/group.service.ts
Labels: Type: Feature, Type: Refactor

#94 Refactor : 로그인 및 회원가입 예외처리
  public/javascript/auth.js
  src/app.controller.ts
  src/auth/auth.service.ts
  src/auth/strategy/local.strategy.ts
  views/auth.hbs
Labels: For: views, Type: Refactor

#99 Feat : 내가 소속된 모든 그룹의 뉴스피드 읽기
  src/newsfeed/newsfeed.controller.ts
  src/newsfeed/newsfeed.service.ts
Labels: Type: Feature, Type: Test

#100 Feature/group 그룹 관련 기능 추가
  src/group/group.controller.ts
  src/group/group.service.ts
  src/group/interface/group.transfer.interface.ts
Labels: Type: Feature

#103 Feat : 뉴스피드 프론트엔드 뉴스피드 읽기,삭제 기능
  public/javascript/newsfeed.js
  src/newsfeed/newsfeed.controller.ts
  src/newsfeed/newsfeed.service.ts
  views/newsfeed.hbs
Labels: Type: Feature, Type: Test

#104 Feature/grouppage 그룹 기능 axios 연결
  public/javascript/create.group.js
  public/javascript/group.joined.list.js
  public/javascript/group.list.js
  public/javascript/hub.group.management.js
  public/javascript/hub.group.members.js
  src/app.controller.ts
  src/group/dto/create.group.dto.ts
  src/group/group.service.ts
  views/hub-group-accept.html
  views/hub-group-invitations.hbs
  views/hub-group-joinedlist.hbs
  views/hub-group-management.hbs
  views/hub-group-members.hbs
  views/partials/header.hbs
  views/partials/hubsidebar.hbs
Labels: For: views, Type: Feature

#105 Refactor : 캘린더 / 그룹이벤트 CRUD 코드 작성 (확인 및 수정필요)
  src/calendar/calendar.controller.ts
  src/calendar/calendar.service.ts
  src/calendar/dto/groupEvent.dto.ts
  src/calendar/dto/updategroupEvent.dto.ts
Labels: Type: Refactor

#108 Feature/grouppage 그룹 상세 정보
  public/javascript/create.group.js
  public/javascript/group.joined.list.js
  public/javascript/group.list.js
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/group/group.service.ts
  views/group-events.hbs
  views/group-events.html
  views/group-timeline.hbs
  views/group-timeline.html
  views/hub-group-accept.html
  views/partials/groupsectionnav.hbs
  views/partials/header.hbs
  views/partials/hubsidebar.hbs
Labels: For: views, Type: Feature, Type: Refactor

#114 Feature/userupdate
  public/javascript/auth.js
  public/javascript/user.js
  src/app.controller.ts
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/guards/jwt-refresh.guard.ts
  src/auth/strategy/jwt-refresh.strategy.ts
  src/auth/strategy/local.strategy.ts
  src/email/email.controller.ts
  src/email/email.service.ts
  src/user/dto/findPassword.dto.ts
  src/user/dto/updatePassword.dto.ts
  src/user/dto/updateUser.dto.ts
  src/user/dto/user.dto.ts
  src/user/user.controller.spec.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.spec.ts
  src/user/user.service.ts
  views/auth.hbs
  views/findPassword.hbs
  views/hub-account-password.hbs
  views/hub-profile-info.hbs
  views/kakao.hbs
  views/partials/header.hbs
  views/partials/hubsidebar.hbs
Labels: For: views, Type: Feature

#119 Feature/grouppage 그룹 수정 axios 연결
  public/javascript/create.group.js
  public/javascript/hub.group.members.js
  src/app.service.ts
  src/group/dto/create.group.dto.ts
  src/group/dto/modify.group.dto.ts
  src/group/group.controller.ts
  src/group/group.service.ts
  views/hub-group-management.hbs
  views/hub-group-members.hbs
Labels: For: views, Type: Feature

#120 Design : 그룹 멤버 role 표시
  public/javascript/member.list.js
Labels: For: views

#131 Refactor/calendar
  public/css/raw/styles.css
  public/javascript/create.event.js
  public/javascript/group.event.list.js
  public/javascript/map.js
  public/javascript/member.list.js
  public/js/calendar.js
  public/js/global/global.popups.js
  src/calendar/calendar.controller.ts
  src/calendar/calendar.module.ts
  src/calendar/calendar.service.ts
  src/calendar/dto/groupEvent.dto.ts
  src/calendar/dto/userEvent.dto.ts
  src/database/entities/groupEvent.entity.ts
  src/database/entities/userEvent.entity.ts
  src/group/group.service.ts
  views/events.hbs
  views/group-events.hbs
Labels: For: views, Type: Feature, Type: Refactor

#139 Refactor/calendar
  public/css copy/raw/calendar.css
  public/css copy/raw/styles.css
  public/css copy/raw/styles.css.map
  public/css copy/styles.min.css
  public/css copy/styles.min.css.map
  public/css copy/vendor/bootstrap.min.css
  public/css copy/vendor/bootstrap.min.css.map
  public/css copy/vendor/simplebar.css
  public/css copy/vendor/tiny-slider.css
  public/javascript/auth.js
  public/javascript/calendar.js
  public/javascript/delete.event.js
  public/javascript/group.event.list.js
  public/js/global/global.popups.js
  src/app.service.ts
  src/calendar/calendar.controller.ts
  src/calendar/calendar.service.ts
  views/events.hbs
  views/group-events.hbs
  views/group-timeline.hbs
Labels: Type: Feature, Type: Refactor

#140 Refactor : 뉴스피드 이미지 수정
  public/js/global/global.hexagons.js
Labels: Type: Errors/Bugs, Type: Refactor

#141 Refactor/events
  public/javascript/calendar.js
  public/javascript/group.event.list.js
  public/js/global/global.popups.js
  src/calendar/calendar.service.ts
  views/hub-group-members.hbs
Labels: For: views, Type: Refactor

#144 Refactor : 뉴스피드 이미지 출력 수정
  .gitignore
  public/javascript/newsfeed.grouptimeline.js
  public/javascript/newsfeed.js
  public/javascript/newsfeed.mylist.js
  public/javascript/newsfeed.utils.js
  public/js/global/global.hexagons.js
  src/newsfeed/newsfeed.controller.ts
  src/newsfeed/newsfeed.service.ts
  src/newsfeed/utills/newsfeed.img.multer.ts
  views/group-timeline.hbs
  views/newsfeed-mylist.hbs
  views/newsfeed.hbs
Labels: Type: Refactor

#152 Refactor/group
  public/javascript/delete.event.js
  src/calendar/calendar.controller.ts
  src/calendar/calendar.service.ts
  src/calendar/dto/event.group.dto.ts
  src/calendar/dto/event.user.dto.ts
  src/calendar/dto/updateUserEvent.dto.ts
  src/calendar/dto/updategroupEvent.dto.ts
  src/common/repository/group.repository.ts
  src/common/repository/tag.group.repository.ts
  src/common/repository/tag.repository.ts
  src/common/repository/user.group.repository.ts
  src/group/dto/modify.group.dto.ts
  src/group/group.controller.ts
  src/group/group.module.ts
  src/group/group.service.ts
  src/group/interface/file.interface.ts
  src/group/interface/get.my.group.list.interface.ts
  src/group/interface/group.join.request.interface.ts
  src/group/interface/group.member.list.interface.ts
  src/group/interface/group.transfer.interface.ts
  src/group/interface/map.group.tag.interface.ts
  src/group/interface/member.group.ids.interface.ts
  src/group/interface/tag.group.ids.interface.ts
  src/group/utils/group.img.multer.ts
Labels: Type: Refactor

#154 Refactor/calendar
  public/javascript/create.event.js
  src/calendar/calendar.controller.ts
  src/calendar/calendar.service.ts
  src/calendar/dto/group.event.dto.ts
  src/calendar/dto/user.event.dto.ts
  src/calendar/interface/event.list.interface.ts
  src/calendar/interface/group.event.list.interface.ts
Labels: Type: Feature, Type: Refactor

#158 Refactor/newsfeed
  public/javascript/newsfeed.grouptimeline.js
  public/javascript/newsfeed.js
  public/javascript/newsfeed.mylist.js
  public/javascript/newsfeed.utils.js
  src/common/repository/group.newsfeed.repository.ts
  src/common/repository/newsfeed.repository.ts
  src/common/repository/newsfeed.tag.repository.ts
  src/common/repository/newsfeedImage.repository.ts
  src/common/repository/tag.repository.ts
  src/common/repository/user.group.repository.ts
  src/database/entities/group-newsfeed.entity.ts
  src/newsfeed/dto/create.newsfeed.dto.ts
  src/newsfeed/dto/modifynewsfeed.check.dto.ts
  src/newsfeed/dto/modinewsfeed-check.dto.ts
  src/newsfeed/dto/newsfeed-check.dto.ts
  src/newsfeed/dto/newsfeed.check.dto.ts
  src/newsfeed/dto/readnewsfeed.check.dto.ts
  src/newsfeed/interface/serch.newsfeed.list.interface.ts
  src/newsfeed/interface/serch.tag.mynewsfeed.interface.ts
  src/newsfeed/interface/serch.tag.newsfeed.interface.ts
  src/newsfeed/newsfeed.controller.spec.ts
  src/newsfeed/newsfeed.controller.ts
  src/newsfeed/newsfeed.module.ts
  src/newsfeed/newsfeed.service.spec.ts
  src/newsfeed/newsfeed.service.ts
  src/newsfeed/utills/newsfeed.img.multer.ts
  views/group-timeline.hbs
  views/newsfeed.hbs
Labels: Type: Refactor

#161 Refactor/group
  public/css/raw/scroll.css
  public/javascript/calendar.js
  public/javascript/create.group.js
  public/javascript/delete.event.js
  public/javascript/group.joined.list.js
  public/javascript/group.list.js
  public/javascript/hub.group.members.js
  public/javascript/member.list.js
  src/common/repository/group.repository.ts
  src/group/group.controller.ts
  src/group/group.service.ts
  views/404.html
  views/auth.hbs
  views/events.hbs
  views/findPassword.hbs
  views/group-events.hbs
  views/group-members.hbs
  views/group-timeline.hbs
  views/groups.hbs
  views/hub-account-password.hbs
  views/hub-group-joinedlist.hbs
  views/hub-group-management.hbs
  views/hub-group-members.hbs
  views/hub-profile-info.hbs
  views/newsfeed-mylist.hbs
  views/newsfeed.hbs
  views/partials/hubsidebar.hbs
Labels: For: views, Type: Refactor

#163 Refactor/newsfeed
  public/javascript/newsfeed.grouptimeline.js
  public/javascript/newsfeed.js
  public/javascript/newsfeed.mylist.js
  public/javascript/newsfeed.utils.js
  src/common/repository/newsfeed.repository.ts
  src/newsfeed/newsfeed.controller.ts
  src/newsfeed/newsfeed.service.ts
  views/group-timeline.hbs
Labels: Type: Feature, Type: Refactor

#164 Refactor : 뉴스피드 마이리스트 수정
  public/javascript/group.list.js
  public/javascript/newsfeed.mylist.js
  src/newsfeed/newsfeed.service.ts
Labels: Type: Errors/Bugs

#168 Reafactor : 그룹-뉴스피드 삭제 및 전체적인 코드 리팩토링
  public/javascript/newsfeed.grouptimeline.js
  public/javascript/newsfeed.js
  public/javascript/newsfeed.mylist.js
  public/javascript/newsfeed.utils.js
  src/app.module.ts
  src/app.service.ts
  src/common/config/typeorm.config.ts
  src/common/repository/group.newsfeed.repository.ts
  src/common/repository/newsfeed.repository.ts
  src/database/entities/group-newsfeed.entity.ts
  src/database/entities/group.entity.ts
  src/database/entities/newsFeed.entity.ts
  src/newsfeed/interface/serch.newsfeed.list.interface.ts
  src/newsfeed/interface/serch.tag.mynewsfeed.interface.ts
  src/newsfeed/interface/serch.tag.newsfeed.interface.ts
  src/newsfeed/newsfeed.controller.spec.ts
  src/newsfeed/newsfeed.controller.ts
  src/newsfeed/newsfeed.module.ts
  src/newsfeed/newsfeed.service.ts
Labels: Type: Refactor

#169 Refactor/newsfeedmylist
  public/javascript/newsfeed.grouptimeline.js
  public/javascript/newsfeed.js
  public/javascript/newsfeed.mylist.js
  public/javascript/newsfeed.utils.js
Labels: Type: Refactor

#170 Feat : 그룹 타임라인 페이지에서 뉴스피드 갯수 수정
  src/app.module.ts
  src/app.service.ts
Labels: Type: Errors/Bugs, Type: Refactor

#174 Refactor : Dto 유효성 검증 정규식 변경
  src/calendar/dto/group.event.dto.ts
  src/calendar/dto/user.event.dto.ts
Labels: Type: Refactor

#175 Refactor : Dto 유효성 검증 정규식 변경
  src/calendar/dto/group.event.dto.ts
  src/calendar/dto/user.event.dto.ts
Labels: Type: Errors/Bugs

#176 Hotfix : sync false 설정
  src/common/config/typeorm.config.ts
Labels: For: Hotfix

#177 Hotfix/pm2
  package.json
Labels: For: Hotfix

#180 Refactor/group image
  public/javascript/calendar.js
  public/javascript/create.group.js
  public/javascript/group.event.list.js
  public/javascript/group.joined.list.js
  public/javascript/group.list.js
  public/javascript/hub.group.members.js
  public/javascript/member.list.js
  public/javascript/newsfeed.utils.js
  src/group/group.module.ts
  src/group/group.service.ts
  src/group/utils/group.img.multer.ts
  views/group-events.hbs
  views/group-timeline.hbs
  views/hub-group-management.hbs
  views/partials/groupsectionnav.hbs
Labels: For: views, Type: Refactor

#183 Refactor : 일정 계속 쌓이는 코드 수정
  public/javascript/calendar.js
  src/calendar/calendar.controller.ts
  src/calendar/calendar.service.ts
  views/events.hbs
Labels: Type: Refactor

#192 Refactor/newsfeedfeedback
  public/javascript/newsfeed.grouptimeline.js
  public/javascript/newsfeed.js
  public/javascript/newsfeed.mylist.js
  public/javascript/newsfeed.utils.js
  src/common/repository/newsfeed.repository.ts
  src/newsfeed/interface/serch.newsfeed.list.interface.ts
  src/newsfeed/newsfeed.controller.ts
  src/newsfeed/newsfeed.service.ts
  views/hub-newsfeed-mylist.hbs
  views/newsfeed.hbs
Labels: Type: Refactor

#194 Refactor/newsfeedfeedback 뉴스피드 헤더바 검색 기능
  public/javascript/header.js
  public/javascript/newsfeed.grouptimeline.js
  public/javascript/newsfeed.js
  public/javascript/newsfeed.mylist.js
  public/javascript/newsfeed.utils.js
  public/javascript/serchnewsfeedtag.js
  public/js/header/header.js
  src/newsfeed/newsfeed.service.ts
  views/hub-newsfeed-mylist.hbs
  views/newsfeed.hbs
  views/partials/header.hbs
  views/serchnewsfeedtag.hbs
Labels: Type: Refactor

#199 Refactor : 뉴스피드 댓글 기능 연동
  public/javascript/newsfeed.utils.js
  src/common/repository/newsfeed.repository.ts
  src/newsfeed/interface/serch.newsfeed.list.interface.ts
  src/newsfeed/interface/serch.tag.mynewsfeed.interface.ts
  src/newsfeed/interface/serch.tag.newsfeed.interface.ts
  src/newsfeed/newsfeed.service.ts
Labels: Type: Refactor

#202 Refactor/newsfeedcomment
  package-lock.json
  package.json
  public/javascript/newsfeed.utils.js
  src/app.module.ts
  src/common/repository/newsfeed.repository.ts
  src/common/repository/user.repository.ts
  src/newsfeed/interface/firstNewsfeed.interface.ts
  src/newsfeed/newsfeed.controller.ts
  src/newsfeed/newsfeed.module.ts
  src/newsfeed/newsfeed.service.ts
  views/partials/header.hbs
Labels: Type: Refactor

#207 Refactor/calendar
  package-lock.json
  package.json
  public/javascript/group.event.list.js
  public/javascript/hub.group.members.js
  src/calendar/calendar.controller.ts
  src/calendar/calendar.module.ts
  src/calendar/calendar.service.ts
  src/calendar/interface/event.list.interface.ts
  src/common/repository/user.group.repository.ts
  views/group-events.hbs
Labels: Type: Refactor

#213 refacotr : 뉴스피드 util 에러 수정
  public/javascript/newsfeed.utils.js
Labels: Type: Errors/Bugs

#215 Refactor : 첫 뉴스피드 작성 시 ES 인덱스 생성 및 뉴스피드,마이뉴스피드 리스트 프로필 이미지 출력
  public/javascript/newsfeed.utils.js
  src/common/repository/newsfeed.repository.ts
  src/newsfeed/newsfeed.service.ts
  views/group-timeline.hbs
  views/hub-newsfeed-mylist.hbs
  views/newsfeed.hbs
Labels: Type: Refactor

#216 Refactor : 헤더 서치바에서 검색시 프로필 이미지 안나오는 문제 수정
  views/serchnewsfeedtag.hbs
Labels: Type: Errors/Bugs

#217 Refactor : ES 클라우드로 변경
  src/app.module.ts
  src/auth/auth.controller.spec.ts
  src/auth/auth.service.spec.ts
  src/calendar/calendar.controller.spec.ts
  src/calendar/calendar.service.spec.ts
  src/comment/comment.controller.spec.ts
  src/comment/comment.service.spec.ts
  src/common/config/elastic.config.ts
  src/email/email.controller.spec.ts
  src/email/email.service.spec.ts
  src/group/group.controller.spec.ts
  src/group/group.controller.ts
  src/group/group.module.ts
  src/group/group.service.spec.ts
  src/group/group.service.ts
  src/newsfeed/newsfeed.controller.spec.ts
  src/newsfeed/newsfeed.module.ts
  src/newsfeed/newsfeed.service.spec.ts
  src/user/user.controller.spec.ts
  src/user/user.service.spec.ts
Labels: Type: Docs/Chore, Type: Feature, Type: Refactor

#222 Refactor/group
  public/javascript/hub.group.members.js
  public/javascript/newsfeed.js
  public/javascript/newsfeed.utils.js
  src/calendar/calendar.module.ts
  src/calendar/calendar.service.ts
  src/common/repository/group.repository.ts
  src/group/group.controller.ts
  src/group/group.service.ts
  src/group/interface/group.member.list.interface.ts
  views/hub-group-members.hbs
Labels: Type: Refactor

#227 Refactor/newsfeed modify
  public/javascript/newsfeed.utils.js
  views/serchnewsfeedtag.hbs
Labels: Type: Refactor

#229 Refactor/group
  public/css/styles.min.css
  public/img/banner/lounge4.png
  public/javascript/hub.group.members.js
  public/javascript/member.list.js
  src/group/group.controller.ts
  src/group/group.service.ts
  views/partials/header.hbs
  views/partials/loader.hbs
Labels: For: views, Type: Refactor

#232 Design : 가입 신청 취소 버튼 삭제
  public/javascript/join.group.list.js
Labels: Type: Feature
